'use client'

import { useState } from 'react'
import { ArrowUpRight, Instagram, MessageCircle, Sparkles, Menu, X, ChevronDown } from 'lucide-react'

const works=[
 {title:'Bridal Details',tag:'BRIDAL • INTRICATE',image:'/mehndi-1.svg'},
 {title:'Floral Flow',tag:'ARABIC • FLORAL',image:'/mehndi-2.svg'},
 {title:'Full Hand',tag:'FULL HAND • DETAIL',image:'/mehndi-3.svg'},
 {title:'Festive Elegance',tag:'FESTIVE • ELEGANT',image:'/mehndi-4.svg'},
]
function Reveal({children,className='' }:{children:React.ReactNode,className?:string}){return <div className={`animate-[fadeUp_.8s_ease-out_both] ${className}`}>{children}</div>}
export default function Page(){
 const [open,setOpen]=useState(false),[sent,setSent]=useState(false)
 const [form,setForm]=useState({name:'',date:'',event:'',requirements:''})
 const wa=(text='')=>`https://wa.me/919727655047${text?`?text=${encodeURIComponent(text)}`:''}`
 const submit=(e:React.FormEvent)=>{e.preventDefault();setSent(true);window.open(wa(`Hi Yashika, I want to enquire about an appointment.\nName: ${form.name}\nDate: ${form.date}\nEvent: ${form.event}\nRequirements: ${form.requirements}`),'_blank')}
 return <div className="min-h-screen overflow-hidden bg-mehndi-cream text-mehndi-ink">
  <style jsx global>{`@keyframes fadeUp{from{opacity:0;transform:translateY(24px)}to{opacity:1;transform:none}}`}</style>
  <header className="fixed top-0 z-50 w-full border-b border-mehndi-gold/20 bg-mehndi-cream/85 backdrop-blur-xl"><div className="mx-auto flex h-20 max-w-6xl items-center justify-between gap-4 px-5 lg:px-8">
   <a href="#home" className="flex items-center gap-3"><div className="grid h-12 w-12 place-items-center rounded-full border border-mehndi-gold bg-white shadow-sm"><span className="font-display text-lg text-mehndi-maroon">YM</span></div><span className="hidden text-xs font-black tracking-[.18em] sm:block">YASHIKA STUDIO</span></a>
   <nav className="hidden items-center gap-7 text-xs font-bold md:flex">{['Work','Services','About','Booking'].map(x=><a key={x} href={'#'+x.toLowerCase()} className="transition hover:text-mehndi-rose">{x}</a>)}</nav>
   <div className="flex items-center gap-2"><a href={wa()} className="rounded-full bg-mehndi-maroon px-5 py-3 text-xs font-extrabold text-white shadow-lg shadow-mehndi-maroon/20 transition hover:-translate-y-1">Book Now</a><button onClick={()=>setOpen(!open)} className="rounded-full border border-mehndi-gold/50 p-3 md:hidden">{open?<X size={17}/>:<Menu size={17}/>}</button></div>
  </div>{open&&<nav className="border-t border-mehndi-gold/20 bg-mehndi-cream px-6 py-5 md:hidden">{['Work','Services','About','Booking'].map(x=><a onClick={()=>setOpen(false)} key={x} href={'#'+x.toLowerCase()} className="block py-3 text-sm font-bold">{x}</a>)}</nav>}</header>
  <main>
   <section id="home" className="relative flex min-h-screen items-center pt-24"><div className="absolute -right-32 top-32 h-96 w-96 rounded-full bg-mehndi-sand/80 blur-3xl"/><div className="mx-auto grid max-w-6xl items-center gap-12 px-5 py-20 lg:grid-cols-2 lg:px-8">
    <Reveal><div className="relative z-10"><p className="text-[10px] font-black tracking-[.28em] text-mehndi-rose">MEHNDI • MAKEUP • BEAUTY</p><h1 className="mt-5 max-w-xl font-display text-6xl leading-[.9] sm:text-7xl lg:text-[88px]">Mehndi that<br/><i className="text-mehndi-rose">speaks</i> beauty.</h1><p className="mt-7 max-w-lg text-sm leading-7 text-[#6c5549]">Elegant mehndi artistry for brides, celebrations and every special moment. Explore the work and contact Yashika directly for your date.</p><div className="mt-7 flex flex-wrap gap-3"><a href="#work" className="rounded-full bg-mehndi-maroon px-6 py-3.5 text-xs font-extrabold text-white shadow-xl shadow-mehndi-maroon/20 transition hover:-translate-y-1">Explore My Work <ArrowUpRight className="ml-1 inline" size={15}/></a><a href="https://www.instagram.com/yashika_mehndi_artist514/" className="rounded-full border border-mehndi-gold/60 px-6 py-3.5 text-xs font-extrabold transition hover:-translate-y-1"><Instagram className="mr-1 inline" size={15}/> Instagram</a></div></div></Reveal>
    <Reveal className="relative z-10 [animation-delay:.15s]"><div className="group relative mx-auto max-w-[500px] rounded-[32px] border border-mehndi-gold p-3 shadow-2xl shadow-mehndi-maroon/10 transition duration-500 hover:rotate-0 lg:rotate-2"><div className="aspect-[4/5] overflow-hidden rounded-[25px] bg-mehndi-sand"><img src="/mehndi-hero.svg" alt="Yashika Mehndi artwork" className="h-full w-full object-cover transition duration-700 group-hover:scale-105"/></div><div className="absolute -bottom-4 -right-4 rounded-2xl bg-mehndi-maroon px-5 py-4 text-[10px] font-black tracking-wider text-white shadow-xl">BRIDAL<br/>MEHNDI</div></div></Reveal>
   </div></section>
   <section id="services" className="bg-mehndi-sand py-24"><div className="mx-auto max-w-6xl px-5 lg:px-8"><div className="mx-auto mb-12 max-w-2xl text-center"><p className="text-[10px] font-black tracking-[.28em] text-mehndi-rose">SERVICES</p><h2 className="mt-3 font-display text-5xl">Signature services</h2><p className="mt-4 text-sm leading-7 text-[#6c5549]">Beautiful styles for weddings, festivals, engagements and special occasions.</p></div><div className="grid gap-4 md:grid-cols-3">{[['01','Bridal Mehndi','Detailed traditional designs made for your most memorable day.'],['02','Arabic Designs','Flowing florals, bold negative space and graceful modern patterns.'],['03','Minimal Mehndi','Simple, elegant designs when you want something light and refined.']].map(([n,t,p],i)=><Reveal key={n} className={`[animation-delay:${i*120}ms]`}><article className="group min-h-52 rounded-3xl border border-mehndi-gold/30 bg-mehndi-paper p-7 transition duration-500 hover:-translate-y-2 hover:shadow-xl hover:shadow-mehndi-maroon/10"><div className="font-display text-2xl text-mehndi-gold">{n}</div><h3 className="mt-6 font-display text-2xl">{t}</h3><p className="mt-2 text-xs leading-6 text-[#6c5549]">{p}</p><Sparkles className="mt-5 text-mehndi-gold transition group-hover:rotate-12" size={17}/></article></Reveal>)}</div></div></section>
   <section id="work" className="py-24"><div className="mx-auto max-w-6xl px-5 lg:px-8"><div className="mb-12 text-center"><p className="text-[10px] font-black tracking-[.28em] text-mehndi-rose">PORTFOLIO</p><h2 className="mt-3 font-display text-5xl">Selected mehndi work</h2><p className="mx-auto mt-4 max-w-xl text-sm leading-7 text-[#6c5549]">A clean, responsive portfolio built around Yashika's mehndi artistry.</p></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{works.map((w,i)=><Reveal key={w.title} className={`[animation-delay:${i*100}ms]`}><figure className="group overflow-hidden rounded-3xl border border-mehndi-gold/25 bg-white shadow-sm transition duration-500 hover:-translate-y-2 hover:shadow-2xl hover:shadow-mehndi-maroon/10"><div className="aspect-[4/5] overflow-hidden bg-mehndi-sand"><img src={w.image} alt={w.title} className="h-full w-full object-cover transition duration-700 group-hover:scale-110"/></div><figcaption className="px-4 py-4 text-[10px] font-black tracking-wider">{w.tag}</figcaption></figure></Reveal>)}</div></div></section>
   <section id="about" className="bg-[#fff3e5] py-24"><div className="mx-auto grid max-w-6xl items-center gap-10 px-5 lg:grid-cols-2 lg:px-8"><Reveal><div className="rounded-3xl border border-mehndi-gold/30 bg-mehndi-paper p-9 shadow-xl shadow-mehndi-maroon/5"><p className="text-[10px] font-black tracking-[.28em] text-mehndi-rose">YASHIKA STUDIO</p><div className="mt-7 border-l-2 border-mehndi-gold pl-5 font-display text-3xl">“Art, elegance & you.”</div><p className="mt-5 text-sm leading-7 text-[#6c5549]">Mehndi artistry created around your occasion, outfit and personal style.</p></div></Reveal><Reveal className="[animation-delay:.15s]"><p className="text-[10px] font-black tracking-[.28em] text-mehndi-rose">MAKE YOUR MOMENT SPECIAL</p><h2 className="mt-3 font-display text-5xl leading-tight">Let's create something beautiful.</h2><p className="mt-5 max-w-lg text-sm leading-7 text-[#6c5549]">Share your event date and requirements to start a booking conversation.</p><a href="#booking" className="mt-6 inline-flex rounded-full bg-mehndi-maroon px-6 py-3.5 text-xs font-extrabold text-white">Start a Booking</a></Reveal></div></section>
   <section id="booking" className="bg-mehndi-sand/70 py-24"><div className="mx-auto grid max-w-6xl gap-10 px-5 lg:grid-cols-2 lg:px-8"><Reveal><p className="text-[10px] font-black tracking-[.28em] text-mehndi-rose">BOOKING</p><h2 className="mt-3 font-display text-5xl">Reserve your date.</h2><div className="mt-8 rounded-3xl border border-mehndi-gold/30 bg-mehndi-paper p-7"><div className="border-b border-mehndi-gold/20 py-4 text-sm"><b className="block">WhatsApp / Contact</b>9727655047</div><div className="border-b border-mehndi-gold/20 py-4 text-sm"><b className="block">Instagram</b>@yashika_mehndi_artist514</div><div className="mt-5 flex flex-wrap gap-3"><a href={wa()} className="rounded-full bg-mehndi-maroon px-5 py-3 text-xs font-extrabold text-white"><MessageCircle className="mr-1 inline" size={15}/> WhatsApp</a><a href="https://www.instagram.com/yashika_mehndi_artist514/" className="rounded-full border border-mehndi-gold/50 px-5 py-3 text-xs font-extrabold">Instagram</a></div></div></Reveal><Reveal className="[animation-delay:.15s]"><form onSubmit={submit} className="rounded-3xl border border-mehndi-gold/30 bg-mehndi-paper p-7 shadow-xl"><h3 className="font-display text-3xl">Quick enquiry</h3>{(['name','date','event'] as const).map(k=><input key={k} required={k==='name'} value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})} placeholder={k==='name'?'Your name':k==='date'?'Event date':'Event / Mehndi type'} className="mt-3 w-full rounded-xl border border-mehndi-gold/25 bg-mehndi-cream px-4 py-3 text-sm outline-none focus:border-mehndi-rose"/>)}<textarea value={form.requirements} onChange={e=>setForm({...form,requirements:e.target.value})} placeholder="Your requirements" className="mt-3 min-h-28 w-full rounded-xl border border-mehndi-gold/25 bg-mehndi-cream px-4 py-3 text-sm outline-none focus:border-mehndi-rose"/><button className="mt-3 w-full rounded-full bg-mehndi-maroon px-6 py-4 text-xs font-extrabold text-white">{sent?'Opening WhatsApp…':'Send Enquiry on WhatsApp'} <ArrowUpRight className="ml-1 inline" size={15}/></button></form></Reveal></div></section>
  </main><footer className="bg-[#28140d] py-7 text-xs text-[#d9c5b7]"><div className="mx-auto flex max-w-6xl items-center justify-between gap-4 px-5 lg:px-8"><span>© 2026 Yashika Mehndi & Beauty Studio</span><a href="#home">Back to top <ChevronDown className="ml-1 inline rotate-180" size={13}/></a></div></footer>
 </div>
}
